"""empty message

Revision ID: 259cc426b91a
Revises: 
Create Date: 2022-03-22 17:10:11.328262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259cc426b91a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qna')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qna',
    sa.Column('qno', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('qas', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('op1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('op2', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('op3', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('op4', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ans', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
