"""empty message

Revision ID: bd22dafce947
Revises: 259cc426b91a
Create Date: 2022-03-22 17:25:58.362527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd22dafce947'
down_revision = '259cc426b91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qna',
    sa.Column('qno', sa.Integer(), nullable=False),
    sa.Column('qas', sa.String(), nullable=True),
    sa.Column('op1', sa.String(), nullable=True),
    sa.Column('op2', sa.String(), nullable=True),
    sa.Column('op3', sa.String(), nullable=True),
    sa.Column('op4', sa.String(), nullable=True),
    sa.Column('ans', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('qno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qna')
    # ### end Alembic commands ###
